### ISSUE TITLE
Go over the DX, identify & fix issues

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#182]
Go over the following commands multiple times 

- [x] check
- [x] init
- [x] create
- [x] apply

Identify bugs or anything that doesn't work as expected. Create a github issue to track bug fixing

**Comment by davidcheung** [comment]
closing this now as I'm able to get the "happy path" setup (stage + prod) with no errors

somethings to note that can be a little annoying 
- cloudfront's propagation time seems to be around 30-40mins, I've multiple times thought my cloudfront/s3 doesn't work because it takes so long
- the circleci pipeline always assumes it will build both stage / prod and is based on HEAD on master, so if that doesn't change, one would have to rerun the pipeline manually, or we can push a commit to master to trigger it
