### ISSUE TITLE
Show & Tell + Workshop within the next week

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#207]

**Comment by bmonkman** [comment]
The hardest part about a workshop would be to get everyone an environment where they can actually run zero..
I think it would be best to set up an environment in advance, then:
- Get people to install the tool
- Walk people through the various commands
- Have people run `check`, `init`, `create`
- Show people what apply looks like, but just kill it after a while
- Show people the diagram, talk a bit about the things that get set up
- Have them pull down a demo infra repo and use the makefile command to set up their kubectl?
- Let them poke around at the cluster we set up?

**Comment by davidcheung** [comment]
This is what i have so far,  still trying to figure out whats a good balance between demo/workshop/explain
#### TODO 

- [x] figure out how to connect to db locally, I've tried to create a service, the pod can use the service name to connect to it, but if i try to `kubectl proxy` and connect to it locally I cant get it to work 
> also tried to tunnel but no success either `kubectl port-forward cheung0724-54dbdcc5b8-8kt9c 5432:cheung0724-staging.ckd8u55vx7su.us-west-2.rds.amazonaws.com:5432` then connect locally 

- [x] how to give access to show-and-tell audience to poke around the cluster? create an IAM and give them a kubeconfig? 

-----
# Show and Tell:


## What is Zero: 

### Current state of Zero:
Boilerplate for infrastructure, containing our best practices

Features
- kubernetes (EKS)
- private image registry
- unified logs
- cert-auto-provision
- auto-scale
- ci/cd pipeline
- ... 


### What we're trying to make Zero into:
An ecosystem for all SaSS building needs, from infrastructure to application logic.



## Workshop:

### Get Zero 
First steps 
```sh
## Linux

curl -OJL https://github.com/commitdev/zero/releases/download/v0.0.1/zero_0.0.1_Linux_x86_64.tar.gz
tar -xvf ./zero_0.0.1_Linux_x86_64.tar.gz
## add zero binary to your current session
export PATH=$PATH:$(pwd)
```

```sh
## mac
## download binary with steps above https://github.com/commitdev/zero/releases/download/v0.0.1/zero_0.0.1_Darwin_x86_64.tar.gz
## or 
brew tap commitdev/zero
brew install zero
```


https://github.com/commitdev/zero/releases/download/v0.0.1/zero_0.0.1_Darwin_x86_64.tar.gz

## New project workshop
### 0. create tokens to get github / circleCI pipeline
```sh
#zero check will create the repo (only need github)
```

### 1. See if you have the dependencies to run Zero 
```sh
zero check
```
### 2. Create your project manifest
```sh
zero init
## fill in all the prompts, verify we have `zero-project.yml`
```
### 3. Scaffold the templates of modules included in your project manifest
```sh
zero create
## check 
```

### 4. Provisioning all the resource / infrastructure 
```
zero apply
```

### 5. Due to time constrain we have already provisioned a stack and this is how you access it 
```sh
wget zero-show-and-tell kubeconfig (preconfigured to work with IAM that can be deleted after)
export KUBECONFIG=~/.kube/zero-show-and-tell
```


### Explain how maintain infra: (workshop)
- Clone the infrastructure repo on a fresh dir to show how teams can collaborate using "infrastructure as code"
- Explain the terraform backend allowing "sync" ` cd kubernetes/terraform/environments/staging/` 
```
terraform {
  backend "s3" {
    bucket         = "cheung0724-staging-terraform-state"
    key            = "infrastructure/terraform/environments/staging/kubernetes"
    encrypt        = true
    region         = "us-west-2"
    dynamodb_table = "cheung0724-staging-terraform-state-locks"
  }
}
```

### How to spin up the dashboard: (workshop)
```
kubectl get secret -o json -n kubernetes-dashboard $(kubectl get secret -n kubernetes-dashboard | grep dashboard-user-token | awk '{print $1}') | jq -r .data.token | base64 -D | pbcopy && \
open "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login" && kubectl proxy
```


### Scaling: (demo only)
add horizontal pod scaler into stage, 
show things that happened 
- pod failed to spin up
- new node created 
- new pod spins up


### How to add a new resource: (workshop: make PR to the infra repo can be done by anyone?)
new ECR repo `terraform/modules/environment/main.tf`
```
module "ecr-utility-images" {
  source = "../../modules/ecr"

  environment       = var.environment
  ecr_repositories  = ["cheung0724-utility-images"]
  ecr_principals    = [data.aws_iam_user.ci_user.arn]
}

```

### Logs (workshop)
 Looking at cloudwatch to see pod's logs from pods,
allowing us to drill down into each services, observing logs across replicas
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2

### How to connect to DB:(maybe)

```yml
# doesnt work
resource "kubernetes_service" "dbservice" {
  metadata {  
    namespace = "dbservice"
    name = "dbservice"
  }
  spec {
    type = "ExternalName"
    external_name = "cheung0724-staging.ckd8u55vx7su.us-west-2.rds.amazonaws.com"
  }
}

resource "kubernetes_deployment" "db_pod" {
  metadata {
    name      = "db-pod"
    namespace = "dbservice"
  }
  spec {
    selector {
      match_labels = {
        "app"    = "db-pod",
      }
    }
    template {
      metadata {
        labels = {
          "app"    = "db-pod",
        }
      }
      spec {
        container {
          name  = "db-pod"
          image = "governmentpaas/psql:latest"
          command = ["tail",  "-f", "/dev/null"]
        }
      }
    }
  }

}
```

### Make a change on backend service (demo?)
- commit change to master
- see circleCI builds
- see deployment change
- curl to api `curl -XPOST https://api-0724.cmt.dev/status/about | jq`

**Comment by davidcheung** [comment]
## workshop

### Get Zero 
First steps 
```sh
## Linux

curl -OJL https://github.com/commitdev/zero/releases/download/v0.0.1/zero_0.0.1_Linux_x86_64.tar.gz
tar -xvf ./zero_0.0.1_Linux_x86_64.tar.gz
## add zero binary to your current session
export PATH=$PATH:$(pwd)
```

```sh
## mac
## download binary with steps above https://github.com/commitdev/zero/releases/download/v0.0.1/zero_0.0.1_Darwin_x86_64.tar.gz
## or 
brew tap commitdev/zero
brew install zero
```

### Create a new project manifest and repos
#### 0. create tokens to get github / circleCI pipeline
```sh
#zero check will create the repo (only need github)
```

#### 1. See if you have the dependencies to run Zero 
```sh
zero check
```
#### 2. Create your project manifest
```sh
zero init
## fill in all the prompts, verify we have `zero-project.yml`
```
#### 3. Scaffold the templates of modules included in your project manifest
```sh
zero create
## check 
```

#### Getting access to the cluster

- to give access
```sh
find the <project-name>-kubernetes-admin-staging role,
add "Trust relationship" of your arn
https://console.aws.amazon.com/iam/home?#/roles/cheung0724-kubernetes-admin-staging?section=trust
{
  "Sid": "",
  "Effect": "Allow",
  "Principal": {
    "AWS": "arn:aws:iam::514226198018:user/david-zero-test"
  },
  "Action": "sts:AssumeRole"
}

CLUSTER_NAME=cheung0724-staging-us-west-2
REGION=us-west-2
ENV=staging
KUBERNETES_ADMIN_ROLEARN=arn:aws:iam::514226198018:role/cheung0724-kubernetes-admin-staging

aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION --role-arn $KUBERNETES_ADMIN_ROLEARN
```

- to get access
```sh
# aws profile / kubeconfig / export AWS_DEFAULT_PROFILE
wget zero-show-and-tell kubeconfig (preconfigured to work with IAM that can be deleted after)
export KUBECONFIG=~/.kube/zero-show-and-tell
```


### Maintaining infrastructure
- Clone the infrastructure repo on a fresh dir to show how teams can collaborate using "infrastructure as code"
- Explain the terraform backend allowing "sync" ` cd kubernetes/terraform/environments/staging/` 
```
terraform {
  backend "s3" {
    bucket         = "cheung0724-staging-terraform-state"
    key            = "infrastructure/terraform/environments/staging/kubernetes"
    encrypt        = true
    region         = "us-west-2"
    dynamodb_table = "cheung0724-staging-terraform-state-locks"
  }
}
```

#### How to spin up the dashboard: (workshop)
```
kubectl get secret -o json -n kubernetes-dashboard $(kubectl get secret -n kubernetes-dashboard | grep dashboard-user-token | awk '{print $1}') | jq -r .data.token | base64 -D | pbcopy && \
open "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login" && kubectl proxy
```


#### Deploy a debug pod for troubleshooting 
Go to your infrastructure repo,
`pushd kubernetes/terraform/environments/staging/`
- add a service to map your database (allowing us to connect to the db using host: db-pod.dbservice )
- pod that has psql built in (allowing us to `kubectl exec -it <podname> sh`)

```
resource "kubernetes_service" "dbservice" {
  metadata {  
    namespace = "dbservice"
    name = "dbservice"
  }
  spec {
    type = "ExternalName"
    external_name = "cheung0724-staging.ckd8u55vx7su.us-west-2.rds.amazonaws.com"
  }
}

resource "kubernetes_deployment" "db_pod" {
  metadata {
    name      = "db-pod"
    namespace = "dbservice"
  }
  spec {
    selector {
      match_labels = {
        "app"    = "db-pod",
      }
    }
    template {
      metadata {
        labels = {
          "app"    = "db-pod",
        }
      }
      spec {
        container {
          name  = "db-pod"
          image = "governmentpaas/psql:latest"
          command = ["tail",  "-f", "/dev/null"]
        }
      }
    }
  }

}
```


#### How to add a new resource: (workshop: make PR to the infra repo can be done by anyone?)

1. adding a new ECR repo `terraform/modules/environment/main.tf`
```
module "ecr-utility-images" {
  source = "../../modules/ecr"

  environment       = var.environment
  ecr_repositories  = ["demo-utility-images"]
  ecr_principals    = [data.aws_iam_user.ci_user.arn]
}

```
2. Testing your changes on Stage
```sh
pushd terraform/environments/staging
terraform init
terraform plan
terraform apply

# https://console.aws.amazon.com/ecr/repositories?#
```
3. Commit your changes
```sh
git checkout -b new-ecr-repo
git add .
git commit -m "new ecr repo"
git push origin new-ecr-repo -u
```

#### Scaling your backend stage deployment
Go to your backend repo
```sh
pushd backend-service/kubernetes/overlays/staging/
```
In your deployment.yml add an autoscaler, then push this to master
```yml
# append this to the file
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myappName
spec:
  maxReplicas: 4
  minReplicas: 1
```
Things that happens
- pod failed to spin up
- new k8s node created from autoscaler
- new pod spins up

### Logs
 Looking at cloudwatch to see pod's logs from pods,
allowing us to drill down into each services, observing logs across replicas
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2
