### ISSUE TITLE
Prototype Node.js BE implementation for upload, download, signed URLs

### ISSUE THREAD

**Issue by GrooveStomp** [commitdev/zero#264]
This Epic intersects with upcoming Helix work, so we're adopting Nodejs for the implementation so that Helix can leverage that themselves.
This ticket is to generate a proof of concept to gain familiarity with Nodejs development and the corresponding AWS SDK APIs for the desired functionality.

**Comment by bmonkman** [comment]
Keep in mind that this will be our first Node support for Zero, so it will include creating a new backend repository, skeleton Node app, etc.

**Comment by GrooveStomp** [comment]
Yeah!
Who should I talk to about the requirements for this?

We can do file upload/download/signed urls easily enough from the BE; but in practice I think uploading from the frontend application would be pretty typical.

The way I see it now is:
- New Nodejs BE repo with upload/download/signed_url functionality
- Changes to infrastructure to support new njs be repo.
- Changes to fe repo to interact with file upload

There are lots of incidentals not mentioned; like new folders in buckets or new buckets? (Just off the top of my head.)

**Comment by bmonkman** [comment]
Yeah on the infra side we will need a new bucket and new cloudfront distribution, if we are using signed URLs there will be special config for that, and we already have the terraform for all that stuff.
Yeah for now I think front end uploading to backend, backend pushing to S3 is fine. At some point we could also add signed upload URLs so that the browser can upload directly to S3 but that can be a future improvement.

**Comment by GrooveStomp** [comment]
Ah, thanks. That's an easier plan to execute on.
I'm not familiar with the cloudfront piece. I'll start poking around that in the infrastructure repo.
