### ISSUE TITLE
Moving application database user/password creation to infra

### ISSUE THREAD

**Issue by davidcheung** [commitdev/zero#303]
Currently the application database gets created in both `deployable-backend` and `deployable-nodejs-backend` with essentially the same script

Problem: 
1. since the script runs in `.tmp/<module>/makefile`, users actually have no way of knowing what their password is
2. database user creation is more of infrastructure than backend application
3. if user rerun zero apply for `backend`, currently it reruns the script, updated the secret, but doesnt update the `db-app-user`'s password, leading to pod fail to start (due to credential mismatch) 
4. code duplication in backend (go/nodejs)

Solution?: 
-[ ] Moving application db-user/password creation into infra

-[ ] bootstrap/secrets: create application database password - in secret manager(because in bootstrap, tfstate deleted, no problem)

- k8s/terraform/modules/k8s/backend-service - reference application secret to create k8s-secret(application password will be available in k8s-secret in s3 state)
  - [ ] shortlived + run once k8s-job with rds_master_password to run sql file from terraform (null_resource + triggger?)

cc @sshi100 @bmonkman

**Comment by bmonkman** [comment]
Sure, I'm fine with moving the provisioning of the password into `backend_service.tf`
I don't think it needs to happen in bootstap/secrets because the passwords will be unique per environment.
Do you want to put them in secrets manager just to make another place where the user can find them? They could most likely also just get them from the secret in k8s. I guess secret manager would be a bit safer.. If they delete the namespace by accident that secret would be gone. Though if you run terraform it would be recreated because it would be pulled out of the saved state.

**Comment by bmonkman** [comment]
This was done
