### ISSUE TITLE
Finish Github Actions pipeline support for applications

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#331]
There was some work done to support Github Actions but it was paused due to lack of support for blocking the pipeline to wait on an approval step.
This support was added recently, and GHA support would be useful for users who want a really streamlined experience, as it won't require additional setup like with CircleCI.

https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/

This will require a bit of digging to find the relevant code, but AFAIK there were branches or forks created for the Go backend, the frontend, and the static site. Hopefully we can reuse most of that work, and then add the additional support for the approval step.
See: https://github.com/commitdev/zero/issues/238

Please add new tickets in each relevant repo as necessary and link them to this Epic.

**Comment by aspcanada** [comment]
I don't think the "approval step" has been baked into the CI workflow on the node and go backends. Was there a reason for omitting them or should I create those relevant issues?

**Comment by davidcheung** [comment]
>I don't think the "approval step" has been baked into the CI workflow on the node and go backends. Was there a reason for omitting them or should I create those relevant issues?

Thanks @aspcanada for bringing this up, yeah unfortunately the Github environments & Protected environments are only available for [**Public Repos**  or **Github enterprise**](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment), but yeah I think would definitely be a good idea to keep a ticket open to seek out other solutions or changes though, and document current behavior (since right now users find out by it not working is not very good)
